FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/student-mobile/ ./apps/student-mobile/

RUN npm install
RUN npm run build:packages
RUN npm run build --workspace=@lockwatch/student-mobile

FROM nginx:alpine AS runner

COPY --from=builder /app/apps/student-mobile/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
